// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function About$default(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "About"), React.createElement("h2", undefined, "Stuff"));
}

var $$default = About$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
